#!/usr/bin/env python3
"""
F-Droid Emulator & Repository Validator
Unified tool for testing Fury's F-Droid Repository.

Modes:
1. --local: Checks local directory structure (metadata, config, keystore).
2. --live: Checks the deployed F-Droid repository (URL access, indexes).
3. --script: Validates the python update script logic/imports.
"""

import os
import sys
import json
import yaml
import requests
import argparse
import traceback
import importlib.util
from pathlib import Path

# Configuration
REPO_URL = "https://fury.untamedfury.space/repo"
EXPECTED_FINGERPRINT = "BD:3D:60:C7:D6:AA:34:20:42:78:62:9B:0F:BC:EC:E7:B6:80:2E:6B:C6:7C:5F:11:12:D2:60:D4:21:86:EE:E6"

def check_local_structure():
    """Validates the local file system layout."""
    print("=== 🏠 Local Structure Check ===")
    
    # 1. Directories
    required_dirs = ['fdroid', 'fdroid/metadata', 'fdroid/repo', 'apks', 'scripts', 'website']
    for d in required_dirs:
        if os.path.isdir(d):
            print(f"  ✓ Directory found: {d}")
        else:
            print(f"  ✗ Directory MISSING: {d}")

    # 2. Config Files
    if os.path.exists("apps.yaml"):
        print("  ✓ apps.yaml found")
        try:
            with open("apps.yaml", 'r') as f:
                data = yaml.safe_load(f)
                count = len(data.get('apps', []))
                print(f"    -> Parsed {count} apps")
        except Exception as e:
            print(f"    ✗ Error parsing apps.yaml: {e}")
    else:
        print("  ✗ apps.yaml MISSING")

    if os.path.exists("fdroid/config.yml"):
        print("  ✓ fdroid/config.yml found")
    else:
        print("  ✗ fdroid/config.yml MISSING")

    # 3. Keystore
    if os.path.exists("fdroid/keystore.p12"):
        size = os.path.getsize("fdroid/keystore.p12")
        print(f"  ✓ Keystore found ({size} bytes)")
    else:
        print("  ✗ Keystore MISSING")

    print("")

def check_live_repo():
    """Checks the publicly accessible F-Droid repository."""
    print(f"=== 🌐 Live Repository Check ({REPO_URL}) ===")
    
    session = requests.Session()
    session.headers.update({'User-Agent': 'Fury-Emulator/2.0'})

    # 1. Index Access
    endpoints = [
        ('index-v1.json', True),
        ('index-v2.json', False), # v2 might not be generated by older servers
        ('index.jar', False)
    ]

    for filename, required in endpoints:
        url = f"{REPO_URL}/{filename}"
        try:
            r = session.head(url, timeout=10)
            if r.status_code == 200:
                print(f"  ✓ {filename} is accessible")
            else:
                mark = "✗" if required else "⚠"
                print(f"  {mark} {filename} returned {r.status_code}")
        except Exception as e:
            print(f"  ✗ Connection failed for {filename}: {e}")

    # 2. APK Availability (Random sample from index if possible)
    # Simplified check for now
    print("  -> Manual check recommended for specific APK downloads.")
    print("")

def validate_script():
    """Imports the main update script to check for syntax errors."""
    print("=== 🐍 Script Validation ===")
    script_path = "scripts/update_fdroid_repo.py"
    
    if not os.path.exists(script_path):
        print(f"  ✗ Script not found: {script_path}")
        return

    try:
        spec = importlib.util.spec_from_file_location("update_fdroid_repo", script_path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        print(f"  ✓ Syntax is valid for {script_path}")
        
        if hasattr(module, 'main'):
            print("  ✓ Found 'main' function")
        else:
            print("  ✗ Function 'main' missing")
            
    except Exception as e:
        print(f"  ✗ Script Import Failed: {e}")
        traceback.print_exc()
    print("")

def main():
    parser = argparse.ArgumentParser(description="Fury's F-Droid Emulator")
    parser.add_argument('--all', action='store_true', help='Run all checks')
    parser.add_argument('--local', action='store_true', help='Check local structure')
    parser.add_argument('--live', action='store_true', help='Check live repository')
    parser.add_argument('--script', action='store_true', help='Validate python script')
    
    args = parser.parse_args()

    if not any(vars(args).values()):
        parser.print_help()
        return

    if args.local or args.all:
        check_local_structure()
    if args.script or args.all:
        validate_script()
    if args.live or args.all:
        check_live_repo()

if __name__ == "__main__":
    main()
